#oracle数据库配置
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.72.4.58:1521:orcl
    username: phis_cq_zx
    password: phis_cq_zx

  #配置使用Redis
  redis:
    database: 0  #使用Redis的0号数据库
    host: 127.0.0.1
    port: 6379
    password:
#缓存使用Redis
  cache:
    type: redis

  mvc:
    view:
      prefix: .html
    static-path-pattern: /**

  ## 是否启动日志SQL语句
  jpa:
    show-sql: true


logging:
  config: classpath:logback.xml

mybatis:
  #配置mapper地址
  mapper-locations: classpath*:/mapper/*.xml
  #配置开启数据库下划线
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8077
  #统一访问前缀
  servlet:
    context-path: /jsg


#登录超时时间设置 (单位:分钟)
time_out: 20
