server:
  port: 8076
  servlet:
    context-path: /jsg

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/examples?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1
  redis:
    database: 0  #使用Redis的0号数据库
    host: 127.0.0.1
    port: 6379
    password:
#缓存使用Redis
  cache:
    type: redis

time_out: 60 #登录超时时间设置 (单位:分钟)
isLogin: true #配置是否需要登录验证
