spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: HIS
    password: 1
  mvc:
    view:
      prefix: .html
    static-path-pattern: /**



logging:
  config: classpath:logback.xml

mybatis:
  #配置mapper地址
  mapper-locations: classpath*:/mapper/*.xml
  #配置开启数据库下划线
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8075
  #统一访问前缀
  servlet:
    context-path: /jsg


