#mysql数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/examples?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1

  #配置使用Redis
  redis:
    database: 0  #使用Redis的0号数据库
    host: 127.0.0.1
    port: 6379
    password:
#缓存使用Redis
  cache:
    type: redis

  mvc:
    view:
      suffix: .html
    static-path-pattern: /**


  ## 是否启动日志SQL语句
  jpa:
    show-sql: true


logging:
  config: classpath:logback.xml

mybatis:
  #配置mapper地址
  mapper-locations: classpath*:/mapper/*.xml
  #配置开启数据库下划线
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8076
  #统一访问前缀
  servlet:
    context-path: /jsg



#登录超时时间设置 (单位:分钟)
time_out: 60
