spring:
  profiles:
    active: dev

logging:
  config: classpath:logback.xml

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  #配置开启数据库下划线
  configuration:
    map-underscore-to-camel-case: true
